Fix gravatar when user has no email
hiqdev/yii2-theme-adminlte pull request #3
Opened 2018-04-24 16:12 UTC by pkolomiy

2018-04-24 16:17 UTC, SilverFire approved these changes

2018-04-24 16:19 UTC, hiqsol commented on src/views/layouts/_sidebar.php
> +                        'email' => Yii::$app->user->identity->email,
```php
'email' => isset(Yii::$app->user->identity->email) ? Yii::$app->user->identity->email : null
```

2018-04-26 08:04 UTC, SilverFire requested changes

2018-04-26 08:04 UTC, SilverFire commented on src/views/layouts/_sidebar.php
> +                        'email' => isset(Yii::$app->user->identity->email) ? Yii::$app->user->identity->email : null,
В PHP 7 можно использовать конструкцию `Yii::$app->user->identity->email ?? null`

2018-04-26 08:04 UTC, SilverFire commented on src/views/widgets/UserMenu.php
> +        'email' => isset(Yii::$app->user->identity->email) ? Yii::$app->user->identity->email : null,
В PHP 7 можно использовать конструкцию `Yii::$app->user->identity->email ?? null`

2018-04-26 08:10 UTC, merged